# Generated by Django 5.2.7 on 2025-10-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
